[workspace]
resolver = "2"
members = [ "amnesia", "byte-sized-chunks", "how-long-is-a-string", "non-std-input", "out-of-order", "please-reboot-the-universe", "stacking-boxes", "there-and-back-again", "three_and_a_bit" , "type-conversion", "walks-like-a-duck-quacks-like-a-duck", "x-marks-the-spot"]
